### ISSUE TITLE
源码启动失败

### ISSUE THREAD

**Issue by Coder-Wjt** [tikmatrix/tiktok-matrix#8]
npm run tauri dev

> tiktok-matrix@1.0.0 tauri
> tauri dev

       Error failed to get cargo metadata: program not found

**Comment by Coder-Wjt** [comment]
安装了，运行报错，64位 Win10 系统：
warning: `TikMatrix` (bin "TikMatrix") generated 3 warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 4m 03s
thread '<unnamed>' panicked at src\interface\rust\desktop.rs:57:63:
called `Result::unwrap()` on an `Err` value: Os { code: 216, kind: Uncategorized, message: "该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by niostack** [comment]
环境问题，你参考这个排查一下：https://github.com/tauri-apps/tauri/issues/5702

**Comment by Coder-Wjt** [comment]
环境应该配置好了，运行 npm run tauri dev 还是报错：
ERROR [TikMatrix] start tiktok-agent failed: 系统找不到指定的文件。 (os error 2)
我查看了 work_dir 目录，里面除了 logs 目录有日志文件，其他文件夹都是空的

**Comment by niostack** [comment]
这个不影响，第一次启动会自动下载资源，客户端没有下载提示吗

**Comment by Coder-Wjt** [comment]
没有提示出现

**Comment by niostack** [comment]
1.检查代码是否是最新的，2.检查客户端日志，右键可以查看控制台，和浏览器一样的控制台

**Comment by Coder-Wjt** [comment]
重新拉取最新版本的源码，成功运行起来了，感谢指引

**Comment by Coder-Wjt** [comment]
环境问题，已解决
